### ISSUE TITLE
Keypoint estimation

### ISSUE THREAD

**Issue by Gbouna** [yizzfz/MiliPoint#7]
Thanks for the great work and for sharing your implementation. I have trained your model for keypoint estimation using your dataset and now have the model weight. I am looking forward to using it for real-time keypoint estimation. 
Given a live stream of data from mmWave radar, is there a way to perform live keypoint estimation? For example, when using Openpose and other related models for keypoint estimation,  given an RGB image, they can provide the corresponding keypoints in real time. Is there a way to do this using your keypoint estimator?

**Comment by yizzfz** [comment]
We do not provide code for real-time inference, but it will be very similar to the procedure implemented in `test.py`: load the model weights, retrieve the 3D point cloud from the live stream (instead of the dataloader), and run something like `res = trainer.predict(plt_model, test_loader)` to obtain the estimated keypoints. You can then visualize the results using, e.g., OpenCV as in `visualize.py`.
